In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]

In [3]:
mylist

[1, 2, 3, 4]

In [5]:
np.array(mylist)

array([1, 2, 3, 4])

In [8]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.linspace(0,5,2)

array([0., 5.])

In [16]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.linspace((0,5,4),(8,9,4))

array([[0.        , 5.        , 4.        ],
       [0.16326531, 5.08163265, 4.        ],
       [0.32653061, 5.16326531, 4.        ],
       [0.48979592, 5.24489796, 4.        ],
       [0.65306122, 5.32653061, 4.        ],
       [0.81632653, 5.40816327, 4.        ],
       [0.97959184, 5.48979592, 4.        ],
       [1.14285714, 5.57142857, 4.        ],
       [1.30612245, 5.65306122, 4.        ],
       [1.46938776, 5.73469388, 4.        ],
       [1.63265306, 5.81632653, 4.        ],
       [1.79591837, 5.89795918, 4.        ],
       [1.95918367, 5.97959184, 4.        ],
       [2.12244898, 6.06122449, 4.        ],
       [2.28571429, 6.14285714, 4.        ],
       [2.44897959, 6.2244898 , 4.        ],
       [2.6122449 , 6.30612245, 4.        ],
       [2.7755102 , 6.3877551 , 4.        ],
       [2.93877551, 6.46938776, 4.        ],
       [3.10204082, 6.55102041, 4.        ],
       [3.26530612, 6.63265306, 4.        ],
       [3.42857143, 6.71428571, 4.        ],
       [3.

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5,3) 

array([[0.74986646, 0.42964445, 0.54223511],
       [0.27921381, 0.50630616, 0.79065779],
       [0.72983983, 0.99728186, 0.96520002],
       [0.22947721, 0.14903263, 0.96553561],
       [0.03315305, 0.74923599, 0.92183304]])

In [22]:
np.random.randn(5,4)

array([[-0.41718504, -1.79526331, -0.22149023,  3.00388271],
       [ 0.16570438,  0.25126246,  0.56040438, -0.54632386],
       [ 0.11042836, -0.36693269,  1.15092625, -1.11647421],
       [-0.61015935,  0.81516964, -0.32826226,  0.54132176],
       [-0.20044919,  0.7255633 , -0.83111535,  2.48219823]])

In [26]:
np.random.randint(50,100,5)

array([58, 93, 71, 88, 69])

In [27]:
np.random.

ValueError: Range cannot be empty (low >= high) unless no samples are taken

In [28]:
lst = range(0,5)

In [29]:
lst

range(0, 5)

In [31]:
lst = list(lst)

In [32]:
lst

[0, 1, 2, 3, 4]

In [33]:
arr = np.arange(1,10)

In [34]:
arrr

NameError: name 'arrr' is not defined

In [35]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr(1:)

SyntaxError: invalid syntax (<ipython-input-36-062cfb0ffe9a>, line 1)

In [37]:
arr(2)

TypeError: 'numpy.ndarray' object is not callable

In [38]:
lst

[0, 1, 2, 3, 4]

In [39]:
lst(3)

TypeError: 'list' object is not callable

In [40]:
arr[3]

4

In [41]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[4:]

array([5, 6, 7, 8, 9])

In [43]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr1 = arr[0:4]

In [49]:
arr1

array([1, 2, 3, 4])

In [50]:
arr1[:] = 99

In [51]:
arr1

array([99, 99, 99, 99])

In [52]:
arr

array([99, 99, 99, 99,  5,  6,  7,  8,  9])

In [53]:
arr2 = arr.copy()

In [54]:
arr2

array([99, 99, 99, 99,  5,  6,  7,  8,  9])

In [55]:
arr2[0:4] = 101

In [56]:
arr2

array([101, 101, 101, 101,   5,   6,   7,   8,   9])

In [57]:
arr

array([99, 99, 99, 99,  5,  6,  7,  8,  9])

In [59]:
new = np.array([1,2,3])

In [60]:
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [61]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr2d[0][1]

10

In [63]:
arr2d[2,1]

40

In [64]:
arr2d[0:2][1:3]

array([[20, 25, 30]])

In [65]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [66]:
arr2d[2]

array([35, 40, 45])

In [67]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [70]:
arr

array([99, 99, 99, 99,  5,  6,  7,  8,  9])

In [73]:
arr = np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
bool_arr = arr>5

In [76]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [77]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[arr<4]

array([0, 1, 2, 3])

In [87]:
arr3 = np.arange(50).reshape(5,10)

In [88]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [89]:
arr3[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [97]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [95]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [96]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
1/0

ZeroDivisionError: division by zero

In [99]:
arr/arr

c:\users\dhdewangan\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
1/arr

c:\users\dhdewangan\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [102]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [103]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [104]:
np.max(arr)

10

In [105]:
np.min(arr)

0

In [106]:
np.log(arr)

c:\users\dhdewangan\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [107]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [111]:
arrnew=np.array([1.56])

In [112]:
np.sin(arrnew)

array([0.99994172])